Fix banner color issue in dark mode
perawallet/pera-android pull request #6
Opened 2024-09-18 12:57 UTC by yasin-ce

Update banner text colors according to the design file.

2024-09-18 14:20 UTC, ehanoc approved these changes

2024-09-18 14:26 UTC, ehanoc requested changes

2024-09-18 14:26 UTC, ehanoc commented on versions.gradle
> +            versionName: "90.19.764-5"
To avoid conflicts on every PR; we can just update this on releases?

2024-09-18 15:08 UTC, yasin-ce commented on versions.gradle
> +            versionName: "90.19.764-5"
We are sending test releases for each ticket. That's why we are updating this value on each ticket branch. Is there any other alternative solution for this?

2024-09-18 19:51 UTC, michaeltchuang commented on versions.gradle
> +            versionName: "90.19.764-5"
> To avoid conflicts on every PR; we can just update this on releases? Unnecessary for `dev` branch

@yasin-ce - I also agree with @ehanoc on this

Maybe this change should be in another PR, but don't manually change the app version name in code, this should be scripted into the CI job so it can be automated for any feature branch builds.  I suggest using the PR branch name and github action run number to help generate the version name (e.g. you can pull this info from github workflow environment variables)

in build.gradle
```
android {
  versionName buildVersionName()
}

def buildVersionName() {
   return "computed version name from branch name"
}
```

Also, the internal version name does seem verbose too (why does sprint number matter?  what happens if a ticket rollovers to next sprint if not merged...do you keep incrementing version name?)

2024-09-19 08:07 UTC, yasin-ce commented on versions.gradle
> +            versionName: "90.19.764-5"
Thanks for the recommendations. I'll create a separate task for this. I will do research and improve the flows. 
@michaeltchuang @ehanoc

2024-09-19 11:46 UTC, ehanoc approved these changes

2024-09-19 11:46 UTC, merged