Bugfix :: koin view model not working ios test app
perawallet/pera-android pull request #72
Opened 2024-12-11 23:43 UTC by alexs60

# Pull Request Template

## Description
- Created a dependency for SQLite Bundled
- Instructed Room Database builder to use the SQLDriver

## Related Issues
- List any related issues or tickets that this pull request addresses.
- For example, closes https://algorandfoundation.atlassian.net/browse/PERA-#

## Checklist
- [X] Have you tested your changes locally?
- [ ] Have you reviewed the code for any potential issues?
- [ ] Have you documented any necessary changes in the project's documentation?
- [ ] Have you added any necessary tests for your changes?
- [ ] Have you updated any relevant dependencies?

## Additional Notes
- Add any additional notes or comments that may be helpful for reviewers.

<img width="487" alt="394953829-37481b9a-db29-496e-8e26-6c640d74734e" src="https://github.com/user-attachments/assets/1d6aa703-fe23-4a53-ae30-4fddbf4103f5" />

2024-12-13 16:13 UTC, mitsinsar requested changes

2024-12-13 16:13 UTC, mitsinsar commented on wallet-sdk/src/androidMain/kotlin/com/algorand/common/account/local/data/database/AccountDatabase.android.kt
> +        .setDriver(BundledSQLiteDriver())
Could you please move this call into `createAccountDatabase`

2024-12-13 16:13 UTC, mitsinsar commented on wallet-sdk/src/iosMain/kotlin/com/algorand/common/account/local/data/database/AccountDatabase.ios.kt
> +        .setDriver(BundledSQLiteDriver())
Could you please move this call into `createAccountDatabase`

2024-12-17 14:47 UTC, alexs60 commented
I have read the CLA Document and I hereby sign the CLA

2024-12-17 15:48 UTC, alexs60 commented
recheck

2024-12-17 16:42 UTC, michaeltchuang commented
recheck

2024-12-17 17:40 UTC, michaeltchuang approved these changes

2024-12-17 18:09 UTC, mitsinsar approved these changes

2024-12-17 18:13 UTC, merged