PERA-747 :: Immersve feature work (with feature flag off)
perawallet/pera-android pull request #9
Opened 2024-10-14 09:47 UTC by mitsinsar

## Summary
- Add In Immersve feature work
- Firebase feature flag added so this PR can be merged earlier (by default it is off, on for debug debug builds)

## Testing
- Immersve is helping test the builds

## Additional Notes
- Closes https://algorandfoundation.atlassian.net/browse/PERA-747

2024-10-14 17:34 UTC, michaeltchuang commented on versions.gradle
> +            versionName: "90.20.747-1"
should PRs that target `dev` branch use `90.X.X` or keep the `5.X.X` convention?  cc: @ehanoc 

(i think you are trying to create a feature build with this name and then remove this change when PR is ready to merge...this should be scripted in CI)

2024-10-15 15:33 UTC, yasin-ce requested changes

2024-10-15 15:33 UTC, yasin-ce commented on app/src/main/java/com/algorand/android/modules/walletconnect/cards/domain/usecase/GetWalletConnectRequestPreselectedAccountAddresses.kt
> +package com.algorand.android.modules.walletconnect.cards.domain.usecase
Copyright comment is missing in this and other few files. Could you review all the new files and add missing comments, please?

2024-10-15 15:33 UTC, yasin-ce commented on app/src/main/java/com/algorand/android/modules/walletconnect/cards/domain/usecase/CacheWalletConnectRequestPreselectedAccountAddressesUseCase.kt
> +    }
This logic looks a bit complex. Could you create a test to make sure this is working in all scenarios?

2024-10-15 15:33 UTC, yasin-ce commented on app/src/main/java/com/algorand/android/modules/card/CardsViewModel.kt
> +    private val _cardsPreviewFlow = MutableStateFlow<CardsPreview>(CardsPreview())
If I'm not mistaken we are not handling the load url error state here. Could you make sure we are handling the error case correctly?

2024-10-18 05:59 UTC, michaeltchuang commented
@mitsinsar - can you add some testing instructions to PR description for reviewers when you get the chance?  Just replace placeholder text

2024-10-18 10:43 UTC, yasin-ce commented on versions.gradle
> +            versionName: "90.20.747-1"
Hi @michaeltchuang, we updated the bitrise flows and @mitsinsar reverted that the version change. So we can mark this as resolved.

2024-10-18 10:44 UTC, yasin-ce approved these changes

2024-10-18 11:42 UTC, michaeltchuang commented
@yasin-ce i don't have access to bitrise yet to check logs, what's the error there?  i assume we can safely ignore?

2024-10-20 21:26 UTC, 1atAlcone approved these changes

2024-11-09 00:02 UTC, merged